{{- if .Values.metabase.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "metabase.fullname" . }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "metabase.fullname" . }}
  minReplicas: {{ .Values.metabase.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.metabase.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.metabase.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.metabase.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.metabase.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.metabase.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
---
{{- if .Values.postgres.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "metabase.fullname" . }}-postgres
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "metabase.fullname" . }}
  minReplicas: {{ .Values.postgres.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.postgres.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.postgres.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.postgres.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.postgres.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.postgres.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
